[package]
name = "cairo-language-server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Language server executable for the Cairo programming language"

[dependencies]
<<<<<<< HEAD
tokio.workspace = true
log.workspace = true

cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "2.6.0-rc.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.6.0-rc.0", features = [
    "env_logger",
] }
||||||| 65da2b480
tokio.workspace = true
log.workspace = true

cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "2.5.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.3", features = [
    "env_logger",
] }
=======
cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "2.5.4" }
>>>>>>> origin/main
