[package]
name = "cairo-language-server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Language server executable for the Cairo programming language"

[dependencies]
tokio.workspace = true
log.workspace = true

<<<<<<< HEAD
cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "2.5.0-dev.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.0-dev.0", features = [
||||||| 1c02dc554
cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "2.4.1" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.4.1", features = [
=======
cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "2.4.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.4.4", features = [
>>>>>>> origin/main
    "env_logger",
] }
